### ISSUE TITLE
New local env are not pushed

### ISSUE THREAD

**Issue by pencilcheck** [xavdid/heroku-config#15]
If I add new env in the env file and push it again to the same destination, the new value doesn't appear in heroku instance.

```
ENV=production
```

then I changed local to

```
ENV=production
HAPPY=yes
```

After I push HAPPY does not appear in `heroku config`

**Comment by xavdid** [comment]
@pencilcheck I wasn't able to reproduce this. I had the following:

```bash
% cat .env
# this file was created automatically by heroku-config

NODE_ENV="production"
BLAH="thing"

% heroku config
=== bgroups Config Vars
BLAH:     thing
NODE_ENV: production
```

I edited the file and ran the following:

```bash
% cat .env
# this file was created automatically by heroku-config

NODE_ENV="production"
BLAH="thing"
HAPPY=yes

% heroku config:push
Successfully wrote settings to Heroku!

% heroku config
=== bgroups Config Vars
BLAH:     thing
HAPPY:    yes
NODE_ENV: production
```

**Comment by pencilcheck** [comment]
Yea it's weird. It used to not work, however I think it fixes itself. And I used a different command:
`heroku config:push -c -o -f .env.staging --remote staging`

I think for now I will close it, hoping it will not pop back again. But appreciate for the time to write a reply.
