### ISSUE TITLE
Line format possibility

### ISSUE THREAD

**Issue by Sajjadhosn** [xavdid/heroku-config#16]
Hello and thank you for this useful tool you've built.

I'm using various Python libraries in an application I'm writing that need env vars and I'm using docker-compose `env_file` directive to pass them to my applications running inside the containers. Problem is, since the line formatting of the `pull` command is set in stone (https://github.com/xavdid/heroku-config/blob/master/util/file.js#L16), some libraries include the additional `"` into account when building URLs and therefore, their client initialization becomes invalid and it won't work. Is it possible that you add a flag or a mechanism, however you see fit, to write to the env file using this format instead:

`heroku config:pull --unquoted` ==> `KEY=VALUE`
`heroku config:pull` ==> `KEY="VALUE"`

**Comment by xavdid** [comment]
Sure! I can do that, I'll get to it this week.

**Comment by xavdid** [comment]
Sorry for the delay here! That's fixed and released in `v1.5.0`
