### ISSUE TITLE
Error Plugin: heroku-config: files attribute must be specified in ..../package.json

### ISSUE THREAD

**Issue by charlesdeb** [xavdid/heroku-config#19]
Whenever I try to run heroku in the CLI I get this error mesage first - and then the CLI appears to work correctly. I can't actually remember why I installed this plug-in in the first place (possibly to try and get wordpress running on heroku?)

The full error message (appears to be duplicated is):
```
(node:23569) Error Plugin: heroku-config: files attribute must be specified in /home/charles/.local/share/heroku/node_modules/heroku-config/package.json
module: @oclif/config@1.6.33
plugin: heroku-config
root: /home/charles/.local/share/heroku/node_modules/heroku-config
See more details with DEBUG=*
(node:23569) Error Plugin: heroku-config: files attribute must be specified in /home/charles/.local/share/heroku/node_modules/heroku-config/package.json
module: @oclif/plugin-legacy@1.0.16
plugin: heroku-config
root: /home/charles/.local/share/heroku/node_modules/heroku-config
See more details with DEBUG=*
```

and sure enough there really is no `files` attribute in the `package.json` - but I can't see anything in the readme for this package telling me why `files` is needed and what it should be set to. I am running ubuntu 16.04 LTS. I am getting this error for all `heroku` CLI commands, including the `heroku help` ones.

I am using heroku-config vs 1.5. and heroku/7.4.11 linux-x64 node-v10.4.1.

Suggestions? Or maybe I should just uninstall `heroku-config` from my system since I'm not sure what I installed it for in the first place...

**Comment by charlesdeb** [comment]
I just upgraded to 1.5.2 and the issue seems to have gone away. Sorry for bugging you.

**Comment by xavdid** [comment]
No problem at all! :) better safe than sorry.
