### ISSUE TITLE
On Windows PowerShell, got error `ERR_INVALID_ARG_TYPE: The "path" argument must be of type string...`

### ISSUE THREAD

**Issue by ot32em** [xavdid/heroku-config#20]
It seems `heroku config:pull` requires the environment variable `HOME` has to be defined,
or the `path.join(process.env.HOME, ...)` will get a argument is non-string type error.

https://github.com/xavdid/heroku-config/blob/master/util/file.js#L146

First time run it on Windows PowerShell got some confused.
So I set `$env:HOME=""` as a workaround.
Then the config output can be generated as expected.

**Comment by xavdid** [comment]
Ah, thank you for finding this!

Just to verify - does the following node snippet produce your home directory in a fresh shell?

```
console.log(require('os').homedir());
```

**Comment by ot32em** [comment]
Yes, it shows my user directory on Windows, => `C:\Users\my_windows_username`.

**Comment by xavdid** [comment]
sweet! Fixed with `1.5.3`, just released.
