### ISSUE TITLE
heroku config:push always gives Warning: The "HEROKU_" namespace is protected and shouldn't be used.

### ISSUE THREAD

**Issue by mariusa** [xavdid/heroku-config#29]
Hi,

heroku config:push always gives the `Warning: The "HEROKU_" namespace is protected and shouldn't be used.`

Could it show this only if setting variables with "HEROKU_" prefix, please? 

Thanks

**Comment by xavdid** [comment]
Hi there!

That warning doesn't come from this package, so I think it's being raised by the CLI (or API) itself. 

If you run `heroku config`, are there keys that include the `HEROKU_` prefix?

**Comment by mariusa** [comment]
Thanks for checking!

There's one, but it's set by Heroku: `HEROKU_POSTGRESQL_GOLD_URL`

That is not in our .env file. The exact command that I run is `heroku config:push -o -f .env`

**Comment by xavdid** [comment]
Ah, I think it's because this package does a read-then-write on the settings:

https://github.com/xavdid/heroku-config/blob/581e00d4ba3fdb5e2a3fee0f0a98f28494f648ae/commands/push.js#L32-L37

IIRC, it does that so it knows which local keys to ignore. I wrote this a long time ago, so it seemed like the best way to do it at the time. 

I _think_ I can safely update it to not re-send keys from the server that didn't change. I'll have to play with it a bit.

It's been this way forever though, it's interesting that no one has mentioned it until now 😄

**Comment by mariusa** [comment]
> It's been this way forever though, it's interesting that no one has mentioned it until now

:)) Even I :) saw it all the time. After checking the 1st time, learned to ignore it. Today was a less busy day so I had time to wonder about it.

> I think it's because this package does a read-then-write on the settings:

Right, looks so from the code. I guess the server expects all keys, doesn't have a batch add/update, like `heroku config:set` works?

https://devcenter.heroku.com/articles/platform-api-reference says
says
`PATCH | used for updating existing objects`, but I guess you tried initially to send only the vars set in local file, that deleted non-existing vars, so you added the `remote: heroku.get(pullUrl)` and merging?

**Comment by mariusa** [comment]
Note: I don't expect  `heroku config:push` to delete remote key values which don't exist locally (too dangerous), only to update & add.

**Comment by xavdid** [comment]
> I guess you tried initially to send only the vars set in local file, that deleted non-existing vars, so you added the remote: heroku.get(pullUrl) and merging?

It must have been something like that, yeah. This is pretty old code, so I don't pretend it was the best way to go about it. I'll take a look this weekend!

**Comment by xavdid** [comment]
@mariusa I've coded this up in https://github.com/xavdid/heroku-config/pull/30. That said, I don't use heroku any longer and don't have unit tests covering this part of the codebase. Do you mind testing it locally to ensure it covers your use case? It should be low-impact. To test:

1. `git clone git@github.com:xavdid/heroku-config.git`
2. `git checkout no-rewrites`
3. `heroku plugins:link .`

Then, when you run `heroku plugins`, it should read:

`heroku-config 1.6.1 (link) /Users/david/projects/heroku-config`

You'll be able to use the config commands like normal. If you feel confident with the change, let me know and I'll merge and release.

Thank you!

**Comment by mariusa** [comment]
Thanks David! I tested it and it works. New settings are written properly and the incorrect `Warning` is gone.

**Comment by xavdid** [comment]
Perfect! Released as `v.1.6.2`. You can run `heroku plugins:update` to pull it down. You should also run `heroku plugins:unlink heroku-config`, so you don't use your locally cloned version.

**Comment by mariusa** [comment]
Thank you! Done and tested that again.
