### ISSUE TITLE
Plugin is invalid

### ISSUE THREAD

**Issue by remy727** [xavdid/heroku-config#31]
```
Installing plugin heroku-config... failed
 ›   Error: plugin is invalid
```
- OS: Ubuntu 22.10
- Heroku CLI version: `heroku/8.0.2 linux-x64 node-v16.19.0`

**Comment by remy727** [comment]
Thank you for confirming.
Yeah, I am having the same issue for other plugins such as `heroku-accounts`
I am closing this now.

**Comment by xavdid** [comment]
No worries!

Could you open a ticket on [the CLI repo](https://github.com/heroku/cli) so they're aware?

**Comment by remy727** [comment]
Good idea. I created [#2277](https://github.com/heroku/cli/issues/2277)
