### ISSUE TITLE
push with clean fails as it tries to delete the HEROKU administered variables

### ISSUE THREAD

**Issue by ruchikasb** [xavdid/heroku-config#32]

**Comment by xavdid** [comment]
Can you give examples of the heroku variables it's failing to delete?

**Comment by ruchikasb** [comment]
"Cannot overwrite attachment values DATABASE_URL"

**Comment by xavdid** [comment]
Ok, I have what should be a fix up. I wasn't able to test it myself, so do you mind doing that?

Instructions:

1. `git clone git@github.com:xavdid/heroku-config.git`
2. `git checkout no-write-heroku-urls`
3. `heroku plugins:link .`

Then, when you run `heroku plugins`, it should mention (link)

You'll be able to use the config commands like normal. If you feel confident with the change, let me know and I'll merge and release.

**Comment by ruchikasb** [comment]
will test and let you know

**Comment by ruchikasb** [comment]
Update to DATABASE_URL
Also, for shared database, Heroku generates a random Variable like HEROKU_POSTGRESQL_RED, general format is HEROKU__

**Comment by ruchikasb** [comment]
It still behaves the same.
Plugin link is there
 heroku-builds 0.0.29
 **heroku-config 1.6.2 (link) /home/jenkins/heroku-config**
 heroku-repo 1.0.14
 heroku-slugs 1.1.0

But when doing clean
I still get 
No updated values to write; skipping
18:09:59   ▸    Cannot overwrite attachment values DATABASE_URL,
18:09:59   ▸    HEROKU_POSTGRESQL_MAUVE_URL.

**Comment by xavdid** [comment]
Apologies, I had a missing pair of parens in my logic. I've updated it in https://github.com/xavdid/heroku-config/pull/33/commits/9bbbee001a4b06f78f427806324aa546787681eb.

Could you `git pull` in your clone and try again?

**Comment by ruchikasb** [comment]
This change is working. Verified.

**Comment by xavdid** [comment]
This is released in 1.6.3.

Thank you!

**Comment by ruchikasb** [comment]
Thank you !
