### ISSUE TITLE
Wont work if there is a space before or after the = sign

### ISSUE THREAD

**Issue by GaryTowers** [xavdid/heroku-config#6]
Great plugin! This saved me a lot of time.

However I found an issue. The plugin wont upload the `.env` file if an ENV var has a space has spaces before or after the equal

- 🚫 `MY_ENV_VAR = XYZ` 
- 🚫 `MY_ENV_VAR= XYZ`
- 🚫 `MY_ENV_VAR =XYZ`
- ✅ `MY_ENV_VAR=XYZ`

The tool returns `Successfully wrote settings to Heroku!` in all cases.

**Comment by xavdid** [comment]
@GaryTowers thanks for the report! I'll look into this

**Comment by xavdid** [comment]
@GaryTowers all set! it should be much for forgiving with what's considered an invalid line now (and also warn about them). Thanks for the report!

**Comment by GaryTowers** [comment]
Awesome thanks @xavdid !!! Not only fixed it but improved it ⭐️!

**Comment by xavdid** [comment]
You're welcome! that's what i'm here for. 😀
